service: prerender

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

package:
  exclude:
    - README.md
    - .github/**
    - .idea/**

functions:
  render:
    handler: handler.render
    timeout: 59
    memorySize: 2048
    maximumEventAge: 600
    maximumRetryAttempts: 0