name: CI

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          architecture: 'x64'

      - name: Install NPM dependencies
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install --only=production

      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        uses: serverless/github-action@v2
        with:
          args: deploy --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        uses: serverless/github-action@v2
        with:
          args: deploy --stage production --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
